fn main() {
    panic!("Welcome in the world of errors handling");
}
